spring:
  datasource:
    url: jdbc:mysql://10.30.2.1:3306/test
    username: chao
    password: wuyongdezhanghao
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  data:
    mongodb:
      database: user
      host: 10.30.2.1
      port: 27001
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  dubbo:
    application:
      id: live-dubbo-provider
      name: live-dubbo-provider
    registry:
      address: zookeeper://10.30.2.3:2181?backup=10.30.2.2:2181,10.30.2.1:2181
    server: true
    protocol:
      name: dubbo
      port: 20880
swagger:
  enable: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xh.springbootshiro.entity
